project:
  type: website
  output-dir: _site

website:
  title: ""
  site-url: "https://blithe-labs.github.io/course-uncertainty-in-ml/"
  navbar: false

execute:
  freeze: auto
format:
  html:
    theme: [default, styles/custom.scss]
