project:
  type: website
  output-dir: _site
  resources:
    - interactive/dist/**

website:
  title: "Uncertainty & Anomaly Detection"
  site-url: "https://blithe-labs.github.io/course-uncertainty-in-ml/"
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lectures"
        href: lecture/intro.qmd
      - text: "Interactive"
        href: interactive.qmd

format:
  html:
    theme: default
    toc: true

execute:
  freeze: auto